x-default: &default
  working_dir: /workspace
  tty: true
  restart: always

x-mount_local: &mount_local
  user: foo
  env_file:
    - .env
  entrypoint: bash
  volumes:
    - $PJ_DIR:/workspace

services:
  sandbox:
    image: asia.gcr.io/linalgo/${PKG_NAME}
    <<: [ *default ]
    build:
      context: $PJ_DIR
      dockerfile: docker/sandbox/Dockerfile
      args:
        - PY_VER=310
        - EXTRA=all

  dev:
    image: asia.gcr.io/linalgo/${PKG_NAME}:dev
    container_name: wsd-dev
    <<: [ *default ]
    build:
      context: $PJ_DIR
      dockerfile: docker/sandbox/Dockerfile
      args:
        - PY_VER=310
        - EXTRA=dev
  vanilla:
    image: asia.gcr.io/linalgo/${PKG_NAME}:vanilla-py310
    build:
      context: $PJ_DIR
      dockerfile: docker/vanilla/Dockerfile
      args:
        - PY_TAG=3.10-slim
      target: dev
