x-default: &default
  working_dir: /workspace
  tty: true
  restart: always

x-mount_local: &mount_local
  user: foo
  entrypoint: bash
  volumes:
    - ${PJ_DIR}:/workspace

services:
  sandbox:
    image: asia.gcr.io/linalgo/${PKG_NAME}
    <<: [ *default, *mount_local ]
    build:
      context: ${PJ_DIR}
      dockerfile: docker/sandbox/Dockerfile
      args:
        - PY_VER=310
        - EXTRA=all
    volumes:
      - ${PJ_DIR}:/workspace

  dev:
    image: asia.gcr.io/linalgo/${PKG_NAME}:dev
    container_name: wsd-dev
    <<: [ *default, *mount_local ]
    build:
      context: ${PJ_DIR}
      dockerfile: docker/sandbox/Dockerfile
      args:
        - PY_VER=310
        - EXTRA=dev
