name: CI

on:
  push:
    branches: ["master", "develop", "v*.*.*", "hotfix/*/*", "fix/*", "maint/*"]
  pull_request:
    branches: ["master"]

jobs:
  build_only:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.filter.outputs.workflows}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          # Copy envs
          cp .env.example .env

          # Remove the rc tag
          sed -i -E 's/(version *= *")([0-9]+\.[0-9]+(\.[0-9]+)?)(rc[0-9]+)?(")/\1\2\5/' ./pyproject.toml

          # Install task
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

          # Install uv
          task install_uv

          # Set python version
          uv venv --python=3.10
          source .venv/bin/activate

          # Install pre-commit
          uv pip install pre-commit=='3.8.0'
          pre-commit install

          # Build
          task build
        shell: bash

  build_mac:
    if: github.event_name == 'push'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on macOS
        run: |
          # Copy envs
          cp .env.example .env

          # Remove the rc tag
          sed -i '' -E 's/(version *= *")([0-9]+\.[0-9]+(\.[0-9]+)?)(rc[0-9]+)?(")/\1\2\5/' ./pyproject.toml

          # Install task
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

          # Install uv
          task install_uv

          # Set python version
          uv venv --python=3.10
          source .venv/bin/activate

          # Install pre-commit
          uv pip install pre-commit=='3.8.0'
          pre-commit install

          # Build
          task build.wheel

          # Install package
          sudo uv pip install $(ls /tmp/wheels | sed 's|^|/tmp/wheels/|') --system

        shell: bash
